# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyle Piira
email: contact@kylepiira.com
description: > # this means to ignore newlines until "baseurl:"
  I am a technology enthusiast who is familiar with maintaining server infrastructure, and building consumer/enterprise facing solutions to 21st century problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kylepiira.com" # the base hostname & protocol for your site
twitter_username: KylePiira
github_username:  KylePiira

# Build settings
markdown: kramdown

# Theme
theme: cayman
